font_size            16
font_family          Hack Nerd Font Mono Regular
bold_font            Hack Nerd Font Mono Bold
italic_font          Hack Nerd Font Mono Italic
bold_italic_font     Hack Nerd Font Mono Bold Italic
adjust_line_height 105%

symbol_map U+e0a0-U+e0a3,U+e0c0-U+e0c7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ea60-U+ebeb,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f534,U+f0001-U+f1af0 Symbols Nerd Font Mono
