font_family      JetBrains Nerd Font
font_size        16
bold_font        auto
italic_font      auto
bold_italic_font auto
adjust_line_height 110%
adjust_column_width 100%

font_features        JetBrainsMonoNFM-Regular +cv11 +cv12 +cv18
font_features        JetBrainsMonoNFM-Light +cv11 +cv12 +cv18
font_features        JetBrainsMonoNFM-ExtraLight +cv11 +cv12 +cv18
font_features        JetBrainsMonoNFM-SemiBold +cv11 +cv12 +cv18
font_features        JetBrainsMonoNFM-Italic +cv12 +cv16 +cv18 +cv19 +cv20
font_features        JetBrainsMonoNFM-SemiBoldItalic +ss02 +cv12 +cv16 +cv18 +cv19 +cv20

symbol_map U+e0a0-U+e0a3,U+e0c0-U+e0c7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ea60-U+ebeb,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f534,U+f0001-U+f1af0 Symbols Nerd Font Mono
