font_size            16
font_family          Maple Mono NF CN Regular
bold_font            Maple Mono NF CN Bold
italic_font          Maple Mono NF CN Italic
bold_italic_font     Maple Mono NF CN Bold Italic

modify_font          cell_width 100%
modify_font          cell_height 100%

font_features        MapleMono-NF-CN-Regular +cv01 +ss05
font_features        MapleMono-NF-CN-Light +cv01 +ss05
font_features        MapleMono-NF-CN-Bold +cv01 +ss05
font_features        MapleMono-NF-CN-Italic +cv01 +ss05
font_features        MapleMono-NF-CN-BoldItalic +cv01 +ss05

symbol_map U+e0a0-U+e0a3,U+e0c0-U+e0c7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ea60-U+ebeb,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f534,U+f0001-U+f1af0 Symbols Nerd Font Mono
