set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'

# Style
Mauve="#cba6f7"
Text="#cdd6f4"
Teal="#94e2d5"
Red="#f38ba8"
Overlay="#7f849c"
Base="#1e1e2e"

set -g allow-rename on

# Theme 
set -g status-position top
set -g status-left-length 100
set -g status-style "fg=${Text}, bg=default"
set -g status-left "#[fg=${Mauve},bold] #S #[fg=${Text},nobold]| #(echo '#{pane_current_path}' \
  | sed \"s|^$HOME|~|\" \
  | awk -F/ '{ \
      n = NF; \
      if (n > 3) \
        path = $(n-2)\"/\"$(n-1)\"/\"$n; \
      else \
        path = $0; \
      max = 15; \
      if (length(path) > max) \
        print \"..\" substr(path, length(path)-max+4); \
      else \
        print path; \
  }') "
set -g status-right "#{cpu_fg_color} 󰻠 #{cpu_percentage} #[fg=${Mauve},bold]|#{ram_fg_color} 󰍛 #{ram_percentage}"
set -g window-status-current-format "#[fg=${Teal},bold]  #[underscore]#W"
set -g window-status-format " #I:#W"
set -g message-style "fg=${Text},bg=default"
set -g mode-style "fg=${Base},bg=${Text}"
set -g pane-border-style "fg=${Overlay}"
set -g pane-active-border-style "fg=${Teal}"

# Keybindings
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
bind o show-options -g

bind c new-window -c "#{pane_current_path}"
bind K send-keys "clear"\; send-keys "Enter"\; clear-history
bind r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

set -g @vim_navigator_mapping_left "C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Y send-keys -X copy-end-of-line

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

unbind-key -T root C-h
unbind-key -T root C-j
unbind-key -T root C-k
unbind-key -T root C-l
unbind-key -T copy-mode-vi C-h
unbind-key -T copy-mode-vi C-j
unbind-key -T copy-mode-vi C-k
unbind-key -T copy-mode-vi C-l

bind b copy-mode \; send-keys -X start-of-line \; send-keys -X search-backward "❯"
bind F copy-mode \; send-keys -X start-of-line \; send-keys -X search-backward "FCN="

# Pane
bind i run-shell " \
if [ $(( \$(tmux display -p '8*#{pane_width}-20*#{pane_height}') )) -lt 0 ]; then \
  tmux splitw -v -c '#{pane_current_path}'; \
else \
  tmux splitw -h -c '#{pane_current_path}'; \
fi"

bind -n M-O next-layout

bind -n S-Up    resize-pane -U 5
bind -n S-Down  resize-pane -D 5
bind -n S-Left  resize-pane -L 5
bind -n S-Right resize-pane -R 5

# Move window
bind -n M-S-Left swap-window -t -1\; select-window -t -1
bind -n M-S-Right swap-window -t +1\; select-window -t +1

run '~/.tmux/plugins/tpm/tpm'
